/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package esteb.aplication;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import consumoApi.ConsumoApi;
import esteb.aplication.IngresoVehiculoP;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author INSTRUCTOR
 */
public class dashboardVen extends javax.swing.JPanel {
    DefaultTableModel tableModel;
    ConsumoApi consumoApi = new ConsumoApi();
    String idpark;
    String idUser;
    /**
     * Creates new form dashboard
     */
    public dashboardVen(String idpark, String idUser) {
        this.idpark = idpark;
        this.idUser = idUser;
        initComponents();
        init();
    }

    private void init(){
        jTable1.setEnabled(false);
        //CONSULTA PARA LA TABAL GENERAL
        GsonBuilder jsonBuilder = new GsonBuilder();

        tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setNumRows(0);
        Map<String, String> data = new HashMap<>();
        data.put("idpark", idpark);
        JsonObject jsonObject = JsonParser.parseString(consumoApi.consumoGETV1("http://localhost/APIenPHP/getAll/obtenerAll.php", data)).getAsJsonObject();
        System.out.println(jsonObject);
        String vehiculoayer = jsonObject.get("vehiculos_ayer").getAsString();

        JsonArray jsonArray = jsonObject.getAsJsonArray("registros");

        for (int i = jsonArray.size() - 1; i >= 0; i--) {
            JsonObject registroJson = jsonArray.get(i).getAsJsonObject();
            String placa = registroJson.get("placa").getAsString();
            String tipoVehiculo = registroJson.get("tipovehiculo").getAsString();
            String horaEntrada = registroJson.get("horaentrada").getAsString();
            String estado = registroJson.get("estado").getAsString();
            String horaSalida = registroJson.get("horasalida").getAsString();
            String costoTotal = registroJson.get("costototal").getAsString();

            Object[] temp = {placa, tipoVehiculo, horaEntrada, estado, horaSalida, costoTotal};
            tableModel.addRow(temp);
        }

        //CONSULTA PARA LABEL DE VEHICULOS INGRESADOS
        int numVehiculos = jsonArray.size();
        int ayervehiculo = Integer.parseInt(vehiculoayer);
        labelIngresadosNum.setText(String.valueOf(numVehiculos));
        vehciulosAyer.setText(""+String.valueOf(ayervehiculo-numVehiculos)+" Que el dia de ayer");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgBorder = new esteb.swing.PanelUI();
        panelUI1 = new esteb.swing.PanelUI();
        jLabel1 = new javax.swing.JLabel();
        labelIngresadosNum = new javax.swing.JLabel();
        vehciulosAyer = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(17, 17, 17));

        bgBorder.setBackground(new java.awt.Color(236, 236, 236));
        bgBorder.setRoundbottomLeft(50);
        bgBorder.setRoundtopLeft(50);

        panelUI1.setBackground(new java.awt.Color(255, 255, 255));
        panelUI1.setRoundbottomLeft(20);
        panelUI1.setRoundbottomRight(20);
        panelUI1.setRoundtopLeft(20);
        panelUI1.setRoundtopRight(20);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(56, 56, 56));
        jLabel1.setText("VEHICULOS INGRESADOS");

        labelIngresadosNum.setBackground(new java.awt.Color(55, 0, 255));
        labelIngresadosNum.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        labelIngresadosNum.setForeground(new java.awt.Color(56, 56, 56));
        labelIngresadosNum.setText("25");

        vehciulosAyer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vehciulosAyer.setForeground(new java.awt.Color(56, 56, 56));
        vehciulosAyer.setText("+0 Que el dia de ayer ");

        javax.swing.GroupLayout panelUI1Layout = new javax.swing.GroupLayout(panelUI1);
        panelUI1.setLayout(panelUI1Layout);
        panelUI1Layout.setHorizontalGroup(
            panelUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUI1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panelUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUI1Layout.createSequentialGroup()
                        .addComponent(labelIngresadosNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vehciulosAyer))
                    .addComponent(jLabel1))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        panelUI1Layout.setVerticalGroup(
            panelUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUI1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIngresadosNum)
                    .addComponent(vehciulosAyer))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        btnIngresar.setBackground(new java.awt.Color(56, 56, 56));
        btnIngresar.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar Vehiculo");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnSalida.setBackground(new java.awt.Color(56, 56, 56));
        btnSalida.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnSalida.setForeground(new java.awt.Color(255, 255, 255));
        btnSalida.setText("Salida Vehiculo");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "PLACA", "TIPO VEHICULO", "HORA INGRESO", "ESTADO", "HORA SALIDA", "TOTAL PAGO"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout bgBorderLayout = new javax.swing.GroupLayout(bgBorder);
        bgBorder.setLayout(bgBorderLayout);
        bgBorderLayout.setHorizontalGroup(
            bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(bgBorderLayout.createSequentialGroup()
                        .addComponent(panelUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        bgBorderLayout.setVerticalGroup(
            bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgBorderLayout.createSequentialGroup()
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SalidaVehiculo salidaVehiculo = new SalidaVehiculo(idpark);
        Container container = this.getParent();

        if (container != null) {
            container.removeAll();
            salidaVehiculo.setSize(container.getSize());
            salidaVehiculo.setLocation(0, 0);
            // Agregar el panel de ingreso de vehículos al contenedor
            container.add(salidaVehiculo);

            container.repaint();
            container.revalidate();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {
        IngresoVehiculoP ingresoVehiculoPanel = new IngresoVehiculoP(idpark, null, idUser);
        Container container = this.getParent();

        if (container != null) {
            container.removeAll();
            ingresoVehiculoPanel.setSize(container.getSize());
            ingresoVehiculoPanel.setLocation(0, 0);
            // Agregar el panel de ingreso de vehículos al contenedor
            container.add(ingresoVehiculoPanel);

            container.repaint();
            container.revalidate();
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private esteb.swing.PanelUI bgBorder;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelIngresadosNum;
    private esteb.swing.PanelUI panelUI1;
    private javax.swing.JLabel vehciulosAyer;
    // End of variables declaration//GEN-END:variables
}
