/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package esteb.aplication;
import esteb.aplication.IngresoVehiculoP;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author INSTRUCTOR
 */
public class EditarVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form dashboard
     */
    public EditarVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgBorder = new esteb.swing.PanelUI();
        panelUI1 = new esteb.swing.PanelUI();
        inputPlaca = new javax.swing.JTextField();
        inputTipoVehiculo = new javax.swing.JTextField();
        inputMarca = new javax.swing.JTextField();
        inputModelo = new javax.swing.JTextField();
        inputColor = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(17, 17, 17));

        bgBorder.setBackground(new java.awt.Color(216, 216, 216));
        bgBorder.setRoundbottomLeft(50);
        bgBorder.setRoundtopLeft(50);

        panelUI1.setBackground(new java.awt.Color(236, 236, 236));
        panelUI1.setRoundbottomLeft(25);
        panelUI1.setRoundbottomRight(25);
        panelUI1.setRoundtopLeft(25);
        panelUI1.setRoundtopRight(25);

        inputPlaca.setBackground(new java.awt.Color(255, 255, 255));
        inputPlaca.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        inputPlaca.setForeground(new java.awt.Color(0, 0, 0));
        inputPlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        inputTipoVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        inputTipoVehiculo.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        inputTipoVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        inputTipoVehiculo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        inputMarca.setBackground(new java.awt.Color(255, 255, 255));
        inputMarca.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        inputMarca.setForeground(new java.awt.Color(0, 0, 0));
        inputMarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        inputModelo.setBackground(new java.awt.Color(255, 255, 255));
        inputModelo.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        inputModelo.setForeground(new java.awt.Color(0, 0, 0));
        inputModelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        inputColor.setBackground(new java.awt.Color(255, 255, 255));
        inputColor.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        inputColor.setForeground(new java.awt.Color(0, 0, 0));
        inputColor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnRegistrar.setBackground(new java.awt.Color(100, 205, 51));
        btnRegistrar.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("EDITAR");

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EDITAR VEHICULO");

        javax.swing.GroupLayout panelUI1Layout = new javax.swing.GroupLayout(panelUI1);
        panelUI1.setLayout(panelUI1Layout);
        panelUI1Layout.setHorizontalGroup(
            panelUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUI1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelUI1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputPlaca)
                    .addComponent(inputTipoVehiculo)
                    .addComponent(inputMarca)
                    .addComponent(inputModelo)
                    .addComponent(inputColor, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUI1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUI1Layout.setVerticalGroup(
            panelUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUI1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(inputPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgBorderLayout = new javax.swing.GroupLayout(bgBorder);
        bgBorder.setLayout(bgBorderLayout);
        bgBorderLayout.setHorizontalGroup(
            bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(panelUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        bgBorderLayout.setVerticalGroup(
            bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private esteb.swing.PanelUI bgBorder;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField inputColor;
    private javax.swing.JTextField inputMarca;
    private javax.swing.JTextField inputModelo;
    private javax.swing.JTextField inputPlaca;
    private javax.swing.JTextField inputTipoVehiculo;
    private javax.swing.JLabel jLabel1;
    private esteb.swing.PanelUI panelUI1;
    // End of variables declaration//GEN-END:variables
}
