/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package esteb.aplication;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import consumoApi.ConsumoApi;
import esteb.aplication.IngresoVehiculoP;

import javax.swing.*;
import java.awt.*;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author INSTRUCTOR
 */
public class InformarcionParqueadero extends javax.swing.JPanel {
    ConsumoApi consumoApi = new ConsumoApi();
    Gson gson = new Gson();
    String idparqueadero;
    String idUser;

    /**
     * Creates new form dashboard
     */

    public InformarcionParqueadero(String idparqueadero, String idUser) {
        initComponents();
        this.idparqueadero = idparqueadero;
        this.idUser = idUser;
        init();
    }

    public void init(){
        Map<String, String> data = new HashMap<>();
        data.put("idparqueadero", idparqueadero);
        JsonObject response = gson.fromJson(consumoApi.consumoGETV1("http://localhost/APIenPHP/getAll/adivinaElPrecio.php", data), JsonObject.class);
        System.out.println(response);
        infoPriceCamioneta.setText(response.get("costotarifacamioneta").getAsString());
        InfoPrecioCamion.setText(response.get("costotarifacamion").getAsString());
        InfoPrecioMoto.setText(response.get("costotarifamoto").getAsString());
        InfoPrecioCarro.setText(response.get("costotarifacarro").getAsString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgBorder = new esteb.swing.PanelUI();
        labeldash = new javax.swing.JLabel();
        infoPriceCamioneta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InfoPrecioCamion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        InfoPrecioMoto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        InfoPrecioCarro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        fondoItemsQuemados = new esteb.swing.PanelUI();
        inputDireccion = new javax.swing.JTextField();
        lbDireccion = new javax.swing.JLabel();
        inpoutNombreP = new javax.swing.JTextField();
        lbNombreP = new javax.swing.JLabel();

        setBackground(new java.awt.Color(17, 17, 17));

        bgBorder.setBackground(new java.awt.Color(236, 236, 236));
        bgBorder.setRoundbottomLeft(50);
        bgBorder.setRoundtopLeft(50);

        labeldash.setBackground(new java.awt.Color(255, 255, 255));
        labeldash.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        labeldash.setForeground(new java.awt.Color(0, 0, 0));
        labeldash.setText("INFORMACION PARQUEADERO");

        infoPriceCamioneta.setBackground(new java.awt.Color(255, 255, 255));
        infoPriceCamioneta.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        infoPriceCamioneta.setForeground(new java.awt.Color(51, 51, 51));
        infoPriceCamioneta.setText("$ 0");
        infoPriceCamioneta.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Camioneta:");

        InfoPrecioCamion.setBackground(new java.awt.Color(255, 255, 255));
        InfoPrecioCamion.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        InfoPrecioCamion.setForeground(new java.awt.Color(51, 51, 51));
        InfoPrecioCamion.setText("$ 0");
        InfoPrecioCamion.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Camion:");

        InfoPrecioMoto.setBackground(new java.awt.Color(255, 255, 255));
        InfoPrecioMoto.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        InfoPrecioMoto.setForeground(new java.awt.Color(51, 51, 51));
        InfoPrecioMoto.setText("$ 0");
        InfoPrecioMoto.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Moto:");

        InfoPrecioCarro.setBackground(new java.awt.Color(255, 255, 255));
        InfoPrecioCarro.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        InfoPrecioCarro.setForeground(new java.awt.Color(51, 51, 51));
        InfoPrecioCarro.setText("$ 0");
        InfoPrecioCarro.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Carro:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("TARIFAS");

        btnUpdate.setBackground(new java.awt.Color(255, 204, 0));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(51, 51, 51));
        btnUpdate.setText("ACTUALIZAR");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        fondoItemsQuemados.setBackground(new java.awt.Color(255, 255, 255));
        fondoItemsQuemados.setRoundbottomLeft(20);
        fondoItemsQuemados.setRoundbottomRight(20);
        fondoItemsQuemados.setRoundtopLeft(20);
        fondoItemsQuemados.setRoundtopRight(20);

        inputDireccion.setBackground(new java.awt.Color(51, 51, 51));
        inputDireccion.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        inputDireccion.setForeground(new java.awt.Color(204, 204, 204));
        inputDireccion.setText("Calle 27 Cr 18");
        inputDireccion.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        inputDireccion.setEnabled(false);

        lbDireccion.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lbDireccion.setForeground(new java.awt.Color(0, 0, 0));
        lbDireccion.setText("Dirrecion:");

        inpoutNombreP.setBackground(new java.awt.Color(51, 51, 51));
        inpoutNombreP.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        inpoutNombreP.setForeground(new java.awt.Color(204, 204, 204));
        inpoutNombreP.setText("Parquearo 27");
        inpoutNombreP.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        inpoutNombreP.setEnabled(false);
        inpoutNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpoutNombrePActionPerformed(evt);
            }
        });

        lbNombreP.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lbNombreP.setForeground(new java.awt.Color(0, 0, 0));
        lbNombreP.setText("Nombre Parqueadero:");

        javax.swing.GroupLayout fondoItemsQuemadosLayout = new javax.swing.GroupLayout(fondoItemsQuemados);
        fondoItemsQuemados.setLayout(fondoItemsQuemadosLayout);
        fondoItemsQuemadosLayout.setHorizontalGroup(
            fondoItemsQuemadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoItemsQuemadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inpoutNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fondoItemsQuemadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDireccion)
                    .addComponent(inputDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
            .addGroup(fondoItemsQuemadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoItemsQuemadosLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNombreP)
                    .addGap(797, 797, 797)))
        );
        fondoItemsQuemadosLayout.setVerticalGroup(
            fondoItemsQuemadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoItemsQuemadosLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(lbDireccion)
                .addGap(0, 0, 0)
                .addGroup(fondoItemsQuemadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpoutNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(fondoItemsQuemadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoItemsQuemadosLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(lbNombreP)
                    .addContainerGap(83, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout bgBorderLayout = new javax.swing.GroupLayout(bgBorder);
        bgBorder.setLayout(bgBorderLayout);
        bgBorderLayout.setHorizontalGroup(
            bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgBorderLayout.createSequentialGroup()
                        .addComponent(labeldash)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgBorderLayout.createSequentialGroup()
                        .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgBorderLayout.createSequentialGroup()
                                .addComponent(infoPriceCamioneta, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(InfoPrecioCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgBorderLayout.createSequentialGroup()
                                .addComponent(InfoPrecioMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(InfoPrecioCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgBorderLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgBorderLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(382, 382, 382)
                                        .addComponent(jLabel4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgBorderLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(412, 412, 412)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fondoItemsQuemados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 875, Short.MAX_VALUE))
                        .addGap(46, 46, 46))))
            .addGroup(bgBorderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bgBorderLayout.setVerticalGroup(
            bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeldash)
                .addGap(18, 18, 18)
                .addComponent(fondoItemsQuemados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(0, 0, 0)
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoPrecioCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoPriceCamioneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(0, 0, 0)
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoPrecioCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoPrecioMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        Map<String, String> data = new HashMap<>();
        data.put("idparqueadero", idparqueadero);
        data.put("precicamioneta", infoPriceCamioneta.getText());
        data.put("preciocamion", InfoPrecioCamion.getText());
        data.put("preciomoto", InfoPrecioMoto.getText());
        data.put("preciauto", InfoPrecioCarro.getText());
        JsonObject response = gson.fromJson(consumoApi.consumoPOST("http://localhost/APIenPHP/getAll/updatePrecio.php", data), JsonObject.class);
        System.out.println(response);
        if(response.get("status").getAsBoolean()) {
            JOptionPane.showMessageDialog(null, response.get("message").getAsString());
        }else{
            JOptionPane.showMessageDialog(null, response.get("message").getAsString());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackHomeActionPerformed
        Container contentPanel = this.getParent();
        contentPanel.removeAll();
        dashboardVen dash = new dashboardVen(idparqueadero,idUser);
        dash.setSize(contentPanel.getSize());
        dash.setLocation(0, 0);
        contentPanel.add(dash);
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_btnBackHomeActionPerformed

    private void inpoutNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpoutNombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpoutNombrePActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InfoPrecioCamion;
    private javax.swing.JTextField InfoPrecioCarro;
    private javax.swing.JTextField InfoPrecioMoto;
    private esteb.swing.PanelUI bgBorder;
    private javax.swing.JButton btnUpdate;
    private esteb.swing.PanelUI fondoItemsQuemados;
    private javax.swing.JTextField infoPriceCamioneta;
    private javax.swing.JTextField inpoutNombreP;
    private javax.swing.JTextField inputDireccion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labeldash;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbNombreP;
    // End of variables declaration//GEN-END:variables
}
