/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package esteb.aplication;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import consumoApi.ConsumoApi;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;

import javax.swing.*;
import javax.swing.text.*;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.time.DateTimeException;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;

import java.io.File;
import java.io.IOException;

import static org.apache.pdfbox.pdmodel.font.PDType1Font.*;

/**
 *
 * @author EstebanVfx
 */
public class IngresoVehiculoP extends javax.swing.JPanel {
    Gson gson = new Gson();
    ConsumoApi consumoApi = new ConsumoApi();
    String keyParquedero;
    String placa, id_vehiculo, placaGet, precio, idUser;
    /**
     * Creates new form IngresoVehiculo
     */
    public IngresoVehiculoP(String keyParquedero, String placaGet, String idUser) {
        initComponents();
        this.keyParquedero = keyParquedero;
        this.placaGet = placaGet;
        this.idUser = idUser;
        init();
        System.out.println("IngresoVehiculo llamado");
        setPlaca();
    }

    private void init(){
        inputMarca.setText("");
        inputColor.setText("");
        selecinadorTipo.setSelectedItem("");
        labelInfoPrecio.setText("$ 0");
        mostrarHora();
        Timer timer = new Timer(1000, e -> {
            mostrarHora();
        });
        timer.start();
        //FUNCION PARA QUE EL TEXTO ESTE CONTINUAMENTE EN MAYUSCULAS
        letrasPlaca.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                super.keyReleased(e);
                letrasPlaca.setText(letrasPlaca.getText().toUpperCase());
            }
        });

        numerosletrasPlaca.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                super.keyReleased(e);
                numerosletrasPlaca.setText(numerosletrasPlaca.getText().toUpperCase());
            }
        });

        //limitador de caracteres en placa
        PlainDocument doc = new PlainDocument(){
            @Override
            public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
                if(getLength() + str.length() <= 3){
                    super.insertString(offs, str, a);

                    if (getLength() == 3 && Character.isUpperCase(str.charAt(0))) {
                        numerosletrasPlaca.requestFocus();
                    }
                }else{
                    System.out.println("SE LLEGO AL LIMITES y salta al numero");
                }
            }
        };
        letrasPlaca.setDocument(doc);

        PlainDocument docv2 = new PlainDocument(){
          @Override
          public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
              if(getLength() + str.length() <= 3){
                  super.insertString(offs, str, a);
                  System.out.println("SE LLEGO AL LIMITES en letra y numero");
              }
          }
        };
        numerosletrasPlaca.setDocument(docv2);


        //FUNCION OBTENER HORA ACTUAL


        //COMBOBOX
        selecinadorTipo.removeAllItems();
        selecinadorTipo.addItem("SELECCIONE");
        selecinadorTipo.addItem("MOTO");
        selecinadorTipo.addItem("CARRO");
        selecinadorTipo.addItem("CAMIONETA");
        selecinadorTipo.addItem("CAMION");
    }

    public void setPlaca() {
        if(placaGet!=null){
            letrasPlaca.setText(placaGet.substring(0,3).toUpperCase());
            numerosletrasPlaca.setText(placaGet.substring(3,6).toUpperCase());
            btnRegistrar.doClick();
            System.out.println("supuestamente dio");
        }
    }
    private void mostrarHora(){
        LocalTime hora = LocalTime.now();

        DateTimeFormatter formato = DateTimeFormatter.ofPattern("HH:mm:ss");
        String horaFormateada = hora.format(formato);

        labelTime.setText(horaFormateada);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgBorder = new esteb.swing.PanelUI();
        panelPlaca = new javax.swing.JPanel();
        numerosletrasPlaca = new javax.swing.JTextField();
        letrasPlaca = new javax.swing.JTextField();
        guionPlaca = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        selecinadorTipo = new javax.swing.JComboBox<>();
        separador = new javax.swing.JSeparator();
        labelTipo = new javax.swing.JLabel();
        labelHoraIngreso = new javax.swing.JLabel();
        panelTiempo = new esteb.swing.PanelUI();
        labelTime = new javax.swing.JLabel();
        labelMarca = new javax.swing.JLabel();
        labelColor = new javax.swing.JLabel();
        inputColor = new javax.swing.JTextField();
        inputMarca = new javax.swing.JTextField();
        labelPrecio = new javax.swing.JLabel();
        panelPriceHora = new esteb.swing.PanelUI();
        labelInfoPrecio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        bgBorder.setBackground(new java.awt.Color(236, 236, 236));
        bgBorder.setRoundbottomLeft(50);
        bgBorder.setRoundtopLeft(50);

        panelPlaca.setBackground(new java.awt.Color(254, 179, 11));
        panelPlaca.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));

        numerosletrasPlaca.setBackground(new java.awt.Color(254, 179, 11));
        numerosletrasPlaca.setColumns(3);
        numerosletrasPlaca.setFont(new java.awt.Font("Ubuntu", 1, 80)); // NOI18N
        numerosletrasPlaca.setForeground(new java.awt.Color(0, 0, 0));
        numerosletrasPlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numerosletrasPlaca.setText("06G");

        letrasPlaca.setBackground(new java.awt.Color(254, 179, 11));
        letrasPlaca.setColumns(3);
        letrasPlaca.setFont(new java.awt.Font("Ubuntu", 1, 80)); // NOI18N
        letrasPlaca.setForeground(new java.awt.Color(0, 0, 0));
        letrasPlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letrasPlaca.setText("MMM");

        guionPlaca.setBackground(new java.awt.Color(0, 0, 0));
        guionPlaca.setFont(new java.awt.Font("Ubuntu", 1, 80)); // NOI18N
        guionPlaca.setForeground(new java.awt.Color(0, 0, 0));
        guionPlaca.setText("-");

        javax.swing.GroupLayout panelPlacaLayout = new javax.swing.GroupLayout(panelPlaca);
        panelPlaca.setLayout(panelPlacaLayout);
        panelPlacaLayout.setHorizontalGroup(
            panelPlacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPlacaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(letrasPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guionPlaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numerosletrasPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelPlacaLayout.setVerticalGroup(
            panelPlacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlacaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelPlacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letrasPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guionPlaca)
                    .addComponent(numerosletrasPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnRegistrar.setBackground(new java.awt.Color(56, 56, 56));
        btnRegistrar.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("VALIDAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        selecinadorTipo.setBackground(new java.awt.Color(56, 56, 56));
        selecinadorTipo.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        selecinadorTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelTipo.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        labelTipo.setForeground(new java.awt.Color(51, 51, 51));
        labelTipo.setText("TIPO DE VEHICULO:");

        labelHoraIngreso.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        labelHoraIngreso.setForeground(new java.awt.Color(51, 51, 51));
        labelHoraIngreso.setText("HORA ACTUAL DE INGRESO:");

        panelTiempo.setRoundbottomLeft(10);
        panelTiempo.setRoundbottomRight(10);
        panelTiempo.setRoundtopLeft(10);
        panelTiempo.setRoundtopRight(10);

        labelTime.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        labelTime.setForeground(new java.awt.Color(255, 255, 255));
        labelTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTime.setText("13:22");

        javax.swing.GroupLayout panelTiempoLayout = new javax.swing.GroupLayout(panelTiempo);
        panelTiempo.setLayout(panelTiempoLayout);
        panelTiempoLayout.setHorizontalGroup(
            panelTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTiempoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTiempoLayout.setVerticalGroup(
            panelTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        labelMarca.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        labelMarca.setForeground(new java.awt.Color(51, 51, 51));
        labelMarca.setText("MARCA VEHICULO:");

        labelColor.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        labelColor.setForeground(new java.awt.Color(51, 51, 51));
        labelColor.setText("COLOR VEHICULO:");

        inputColor.setBackground(new java.awt.Color(255, 255, 255));
        inputColor.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        inputColor.setForeground(new java.awt.Color(0, 0, 0));
        inputColor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputColor.setText("Verder");

        inputMarca.setBackground(new java.awt.Color(255, 255, 255));
        inputMarca.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        inputMarca.setForeground(new java.awt.Color(0, 0, 0));
        inputMarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputMarca.setText("JEEP");

        labelPrecio.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        labelPrecio.setForeground(new java.awt.Color(51, 51, 51));
        labelPrecio.setText("Tarifa x hora:");

        panelPriceHora.setRoundbottomLeft(10);
        panelPriceHora.setRoundbottomRight(10);
        panelPriceHora.setRoundtopLeft(10);
        panelPriceHora.setRoundtopRight(10);

        labelInfoPrecio.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        labelInfoPrecio.setForeground(new java.awt.Color(255, 255, 255));
        labelInfoPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInfoPrecio.setText("7.000");

        javax.swing.GroupLayout panelPriceHoraLayout = new javax.swing.GroupLayout(panelPriceHora);
        panelPriceHora.setLayout(panelPriceHoraLayout);
        panelPriceHoraLayout.setHorizontalGroup(
            panelPriceHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPriceHoraLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(labelInfoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        panelPriceHoraLayout.setVerticalGroup(
            panelPriceHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPriceHoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInfoPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(100, 205, 51));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("COMFIRMAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INGRESO VEHICULO");

        javax.swing.GroupLayout bgBorderLayout = new javax.swing.GroupLayout(bgBorder);
        bgBorder.setLayout(bgBorderLayout);
        bgBorderLayout.setHorizontalGroup(
            bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPrecio)
                    .addComponent(panelPriceHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(bgBorderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(bgBorderLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgBorderLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgBorderLayout.createSequentialGroup()
                        .addComponent(labelTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                        .addComponent(labelHoraIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233))
                    .addGroup(bgBorderLayout.createSequentialGroup()
                        .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(bgBorderLayout.createSequentialGroup()
                                    .addComponent(panelPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(separador, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE))
                            .addGroup(bgBorderLayout.createSequentialGroup()
                                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(selecinadorTipo, 0, 362, Short.MAX_VALUE)
                                        .addComponent(inputMarca))
                                    .addComponent(labelMarca))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelColor)
                                    .addComponent(panelTiempo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))))
                        .addContainerGap(57, Short.MAX_VALUE))))
        );
        bgBorderLayout.setVerticalGroup(
            bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipo)
                    .addComponent(labelHoraIngreso))
                .addGap(0, 0, 0)
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selecinadorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgBorderLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelMarca))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgBorderLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelColor)))
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPriceHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Map<String, String> insertData = new HashMap<>();
        placa = letrasPlaca.getText()+numerosletrasPlaca.getText();
        System.out.println(placa);
        insertData.put("placa", placa);
        System.out.println(consumoApi.consumoGETV1("http://localhost/APIenPHP/getAll/validarVehiculo.php", insertData));
        JsonParser parser = new JsonParser();
        JsonObject jsonData = parser.parse(consumoApi.consumoGETV1("http://localhost/APIenPHP/getAll/validarVehiculo.php", insertData).toString()).getAsJsonObject();
        if (jsonData.get("status").getAsBoolean()){
            JsonObject data = jsonData.get("data").getAsJsonObject();
            inputMarca.setText(data.get("marca").getAsString());
            inputColor.setText(data.get("color").getAsString());
            String tipovehiculo = data.get("tipovehiculo").getAsString();
            selecinadorTipo.setSelectedItem(tipovehiculo.toUpperCase());
            id_vehiculo = data.get("idvehiculo").getAsString();

            Map<String, String> insertData2 = new HashMap<>();
            insertData2.put("idparqueadero", keyParquedero);
            JsonObject jsonObjPrecio = JsonParser.parseString(consumoApi.consumoGETV1("http://localhost/APIenPHP/getAll/adivinaElPrecio.php", insertData2)).getAsJsonObject();
            if (tipovehiculo.equalsIgnoreCase("moto")) {
                System.out.println("es moto");
                precio = jsonObjPrecio.get("costotarifamoto").getAsString();
            }else if (tipovehiculo.equalsIgnoreCase("carro")) {
                precio = jsonObjPrecio.get("costotarifacarro").getAsString();
            }else if (tipovehiculo.equalsIgnoreCase("camioneta")) {
                System.out.println("es camioneta");
                precio = jsonObjPrecio.get("costotarifacamioneta").getAsString();
            }else if (tipovehiculo.equalsIgnoreCase("camion")) {
                System.out.println("es camion");
                precio = jsonObjPrecio.get("costotarifacamion").getAsString();
            }else{
                precio = "0";
            }
            labelInfoPrecio.setText("$ "+precio);
        }else if(jsonData.get("ingreso").getAsBoolean()){
            int option = JOptionPane.showConfirmDialog(null, jsonData.get("message").getAsString()+"LA DESEA REGISTRAR?", "Confirmación", JOptionPane.OK_CANCEL_OPTION);
            if(option == JOptionPane.OK_OPTION) {
                Container frame = this.getParent();
                frame.removeAll();
                RegistrarVehiculo registrarVehiculo = new RegistrarVehiculo(idUser, keyParquedero, placa);
                registrarVehiculo.setSize(frame.getSize());
                registrarVehiculo.setLocation(0, 0);
                frame.add(registrarVehiculo);
                frame.repaint();
                frame.revalidate();
            }else if (option == JOptionPane.CANCEL_OPTION) {
                System.out.println("CANCEL");
            }else{
                System.out.println("CLOSE");
            }
        }else{
            JOptionPane.showMessageDialog(null, jsonData.get("message").getAsString());
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Map<String, String> insertData = new HashMap<>();
        insertData.put("idvehiculo", id_vehiculo);
        insertData.put("idparqueadero", keyParquedero);
        JsonParser parser = new JsonParser();
        JsonObject jsonPostData = parser.parse(consumoApi.consumoPOST("http://localhost/APIenPHP/getAll/addTicket.php", insertData).toString()).getAsJsonObject();
        if (jsonPostData.get("status").getAsBoolean()) {
            JOptionPane.showMessageDialog(null, jsonPostData.get("message").getAsString());
            genrerarFcaturaPdf();
        }else{
            JOptionPane.showMessageDialog(null, jsonPostData.get("message").getAsString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void genrerarFcaturaPdf(){
        try {
            PDDocument documento = new PDDocument();
            PDPage pagina = new PDPage();
            documento.addPage(pagina);

            PDPageContentStream contentStream = new PDPageContentStream(documento, pagina);
            PDType1Font font = PDType1Font.HELVETICA_BOLD;

            // Agrega estilo al título de la factura (fuente más grande)
            contentStream.setNonStrokingColor(0, 0, 255); // Color azul
            contentStream.beginText();
            contentStream.setFont(font, 30); // Tamaño de fuente más grande
            contentStream.newLineAtOffset(100, 700);
            contentStream.showText("Factura de Parqueadero");
            contentStream.endText();

            // Restaura el tamaño de fuente normal
            contentStream.setFont(font, 12);

            // Agrega estilo al contenido
            contentStream.setNonStrokingColor(0, 0, 0); // Color negro
            contentStream.beginText();
            contentStream.newLineAtOffset(100, 650);
            contentStream.showText("Placa del Vehículo: " + placa);
            contentStream.newLineAtOffset(0, -20);
            contentStream.showText("Hora De Ingreso: " + labelTime.getText());
            contentStream.newLineAtOffset(0, -20);
            contentStream.showText("Tarifa por Hora: $" + precio);
            contentStream.endText();
            contentStream.close();
            String nombreFactura = "factura"+placa+labelTime.getText()+".pdf";
            nombreFactura = nombreFactura.replace(":", "_");
            documento.save(nombreFactura);
            documento.close();
            System.out.println("PDF CREADO");
        }catch (IOException e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private esteb.swing.PanelUI bgBorder;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel guionPlaca;
    private javax.swing.JTextField inputColor;
    private javax.swing.JTextField inputMarca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelColor;
    private javax.swing.JLabel labelHoraIngreso;
    private javax.swing.JLabel labelInfoPrecio;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelTime;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JTextField letrasPlaca;
    private javax.swing.JTextField numerosletrasPlaca;
    private javax.swing.JPanel panelPlaca;
    private esteb.swing.PanelUI panelPriceHora;
    private esteb.swing.PanelUI panelTiempo;
    private javax.swing.JComboBox<String> selecinadorTipo;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
}
