/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package esteb.aplication;
import com.google.gson.*;
import consumoApi.ConsumoApi;
import esteb.aplication.IngresoVehiculoP;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author INSTRUCTOR
 */
public class ListadoVehiculos extends javax.swing.JPanel {
    DefaultTableModel tableModel;
    ConsumoApi consumoApi = new ConsumoApi();
    String idUser;
    String idPark;
    /**
     * Creates new form dashboard
     */
    public ListadoVehiculos(String idUser, String idPark) {
        initComponents();
        this.idUser = idUser;
        this.idPark = idPark;
        init();
    }

    private void init(){

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgBorder = new esteb.swing.PanelUI();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        input_Placa = new javax.swing.JTextField();
        labelDesp = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(17, 17, 17));

        bgBorder.setBackground(new java.awt.Color(236, 236, 236));
        bgBorder.setRoundbottomLeft(50);
        bgBorder.setRoundtopLeft(50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "PLACA", "TIPO VEHICULO", "HORA INGRESO", "ESTADO", "HORA SALIDA", "TOTAL PAGO"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        input_Placa.setBackground(new java.awt.Color(254, 179, 11));
        input_Placa.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        input_Placa.setForeground(new java.awt.Color(0, 0, 0));
        input_Placa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input_Placa.putClientProperty("JTextField.placeholderText", "AAA-098");
        input_Placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input_PlacaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_PlacaKeyReleased(evt);
            }
        });

        labelDesp.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        labelDesp.setForeground(new java.awt.Color(0, 0, 0));
        labelDesp.setText("BUSCAR HISTORICO DE VEHICULO POR PLACA:");

        btnRegistrar.setBackground(new java.awt.Color(56, 56, 56));
        btnRegistrar.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(56, 56, 56));
        btnEditar.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("EDITAR ");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LISTADO VEHICULOS");

        javax.swing.GroupLayout bgBorderLayout = new javax.swing.GroupLayout(bgBorder);
        bgBorder.setLayout(bgBorderLayout);
        bgBorderLayout.setHorizontalGroup(
            bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBorderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bgBorderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgBorderLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgBorderLayout.createSequentialGroup()
                        .addComponent(labelDesp)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bgBorderLayout.createSequentialGroup()
                        .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
                            .addComponent(input_Placa))
                        .addGap(26, 26, 26))))
        );
        bgBorderLayout.setVerticalGroup(
            bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(bgBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnEditar))
                .addGap(44, 44, 44)
                .addComponent(labelDesp)
                .addGap(0, 0, 0)
                .addComponent(input_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        RegistrarVehiculo registrarVehiculo = new RegistrarVehiculo(idUser, idPark, null);
        Container container = this.getParent();

        if (container != null) {
            container.removeAll();
            registrarVehiculo.setSize(container.getSize());
            registrarVehiculo.setLocation(0, 0);
            // Agregar el panel de ingreso de vehículos al contenedor
            container.add(registrarVehiculo);
            container.repaint();
            container.revalidate();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        EditarVehiculo editarVehiculo = new EditarVehiculo();
        Container container = this.getParent();

        if (container != null) {
            container.removeAll();
            editarVehiculo.setSize(container.getSize());
            editarVehiculo.setLocation(0, 0);
            // Agregar el panel de ingreso de vehículos al contenedor
            container.add(editarVehiculo);
            container.repaint();
            container.revalidate();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void input_PlacaKeyPressed(KeyEvent evt) {//GEN-FIRST:event_input_PlacaKeyPressed

    }//GEN-LAST:event_input_PlacaKeyPressed

    private void input_PlacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_PlacaKeyReleased
        if(input_Placa.getText().length()>=4 && input_Placa.getText().length() < 7){
            Map<String, String> getData = new HashMap<>();
            getData.put("placa", input_Placa.getText());
            System.out.println(consumoApi.consumoGETV1("http://localhost/APIenPHP/getAll/obtenerPorPlaca.php", getData));

            GsonBuilder jsonBuilder = new GsonBuilder();

            tableModel = (DefaultTableModel) jTable1.getModel();
            tableModel.setNumRows(0);

            JsonObject jsonObject = JsonParser.parseString(consumoApi.consumoGETV1("http://localhost/APIenPHP/getAll/obtenerPorPlaca.php", getData)).getAsJsonObject();
            System.out.println(jsonObject);

            JsonArray jsonArray = jsonObject.getAsJsonArray("registros");

            for (int i = jsonArray.size() - 1; i >= 0; i--) {
                JsonObject registroJson = jsonArray.get(i).getAsJsonObject();
                String placa = registroJson.get("placa").getAsString();
                String tipoVehiculo = registroJson.get("tipovehiculo").getAsString();
                String horaEntrada = registroJson.get("horaentrada").getAsString();
                String estado = registroJson.get("estado").getAsString();
                String horaSalida = registroJson.get("horasalida").getAsString();
                String costoTotal = registroJson.get("costototal").getAsString();

                Object[] temp = {placa, tipoVehiculo, horaEntrada, estado, horaSalida, costoTotal};
                tableModel.addRow(temp);
            }
        }
    }//GEN-LAST:event_input_PlacaKeyReleased



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private esteb.swing.PanelUI bgBorder;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField input_Placa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelDesp;
    // End of variables declaration//GEN-END:variables
}
