/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package esteb.main;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import esteb.aplication.InformarcionParqueadero;
import esteb.aplication.ListadoVehiculos;
import esteb.login.Login;

import esteb.aplication.ListadoParqueaderos;
import esteb.aplication.ListadoVendedores;

import esteb.aplication.dashboardAdm;


import javax.swing.*;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author INSTRUCTOR
 */
public class AplictionAdm extends javax.swing.JFrame {

    ConsumoAPI consumoAPI = new ConsumoAPI();
    String username;
    String nombre_parqueadero;

    String key_parqueadero;
    /** Creates new form AplictionAdm */
    public AplictionAdm(String username, String key_parqueadero, String nombre_parqueadero) {
        initComponents();
        this.username = username;

        if (key_parqueadero != null && nombre_parqueadero != null) {
            this.key_parqueadero = key_parqueadero;
            this.nombre_parqueadero = nombre_parqueadero;
        }

        init();
        btnDashboardActionPerformed(null);
        setTitle("Spot Master");
    }

    private void init() {
        if (key_parqueadero == null && nombre_parqueadero == null) {
            Gson gson = new Gson();
            Map<String, String> getDatos = new HashMap<>();
            getDatos.put("user", username);

            // Cambia la URL de la API a la nueva ruta
            String apiUrl = "http://localhost/APIenPHP/getAll/getadmin.php";
            String apinombre= "http://localhost/APIenPHP/getAll/PerfilAPi/getInfoPerfil.php";

            String jsonResponse = consumoAPI.consumoGET(apiUrl, getDatos);

            JsonObject jsonObject = JsonParser.parseString(jsonResponse).getAsJsonObject();
            JsonArray datosJson = jsonObject.get("data").getAsJsonArray();

            System.out.println(datosJson);

            key_parqueadero = datosJson.get(0).getAsJsonObject().get("idpark").getAsString();
        } else {

            JLParqueadero.setText(nombre_parqueadero);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorBtnNav = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnVendedores = new javax.swing.JButton();
        btnParquedero = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        JLImg = new javax.swing.JLabel();
        JLNombre = new javax.swing.JLabel();
        JLParqueadero = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        contentPanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedorBtnNav.setBackground(new java.awt.Color(18, 20, 28));
        contenedorBtnNav.setForeground(new java.awt.Color(255, 255, 255));

        btnDashboard.setBackground(new java.awt.Color(18, 20, 28));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("DASHBOARD");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnVendedores.setBackground(new java.awt.Color(18, 20, 28));
        btnVendedores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVendedores.setForeground(new java.awt.Color(255, 255, 255));
        btnVendedores.setText("VENDEDORES");
        btnVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedoresActionPerformed(evt);
            }
        });

        btnParquedero.setBackground(new java.awt.Color(18, 20, 28));
        btnParquedero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnParquedero.setForeground(new java.awt.Color(255, 255, 255));
        btnParquedero.setText("PARQUEADEROS");
        btnParquedero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParquederoActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(18, 20, 28));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 51, 51));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        JLNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLNombre.setForeground(new java.awt.Color(255, 255, 255));
        JLNombre.setText("Administrador");

        JLParqueadero.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout contenedorBtnNavLayout = new javax.swing.GroupLayout(contenedorBtnNav);
        contenedorBtnNav.setLayout(contenedorBtnNavLayout);
        contenedorBtnNavLayout.setHorizontalGroup(
            contenedorBtnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorBtnNavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorBtnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contenedorBtnNavLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(JLImg, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contenedorBtnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLParqueadero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(btnParquedero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        contenedorBtnNavLayout.setVerticalGroup(
            contenedorBtnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorBtnNavLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(contenedorBtnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(contenedorBtnNavLayout.createSequentialGroup()
                        .addComponent(JLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(JLParqueadero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JLImg, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnParquedero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        contentPanel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        contentPanel.setText("LABEL PRINICPAL SIN NADA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenedorBtnNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorBtnNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        contentPanel.removeAll();
        dashboardAdm lidash = new dashboardAdm(key_parqueadero);
        lidash.setSize(contentPanel.getSize());
        lidash.setLocation(0, 0);
        contentPanel.add(lidash);
        repaint();
        revalidate();

    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnParquederoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParquederoActionPerformed
        contentPanel.removeAll();
        ListadoParqueaderos listadoDash = new ListadoParqueaderos();
        listadoDash.setSize(contentPanel.getSize());
        listadoDash.setLocation(0, 0);
        contentPanel.add(listadoDash);
        repaint();
        revalidate();
    }//GEN-LAST:event_btnParquederoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformedAplictionAdm aplicationAdm = new AplictionAdm(user, null, null);
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformedAplictionAdm aplicationAdm = new AplictionAdm(user, null, null);

    private void btnVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendedoresActionPerformed
        contentPanel.removeAll();
        ListadoVendedores listadoDash = new ListadoVendedores();
        listadoDash.setSize(contentPanel.getSize());
        listadoDash.setLocation(0, 0);
        contentPanel.add(listadoDash);
        repaint();
        revalidate();
    }//GEN-LAST:event_btnVendedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplictionAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplictionAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplictionAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplictionAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplictionAdm(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLImg;
    private javax.swing.JLabel JLNombre;
    private javax.swing.JLabel JLParqueadero;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnParquedero;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVendedores;
    private javax.swing.JPanel contenedorBtnNav;
    private javax.swing.JLabel contentPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
