/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package esteb.main;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import esteb.aplication.InformarcionParqueadero;
import esteb.aplication.ListadoVehiculos;
import esteb.aplication.dashboardVen;
import esteb.login.Login;
import javax.swing.*;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author INSTRUCTOR
 */
public class AplictionVen extends javax.swing.JFrame {


    ConsumoAPI consumoAPI = new ConsumoAPI();
    String username;
    String idUser;
    String nombre_parqueadero;

    String key_parqueadero;
    /** Creates new form AplictionAdm */
    public AplictionVen(String username, String key_parqueadero, String nombre_parqueadero, String idUser) {
        initComponents();
        this.username = username;
        this.nombre_parqueadero = nombre_parqueadero;
        this.key_parqueadero = key_parqueadero;
        this.idUser = idUser;
        init();
        btnDashboardActionPerformed(null);
        setTitle("Spot Master");
    }
    private void init(){
        if(key_parqueadero == null && nombre_parqueadero == null) {
            Gson gson = new Gson();
            Map<String, String> getDatos = new HashMap<>();
            getDatos.put("user", username);
            consumoAPI.consumoGET("http://localhost/APIenPHP/getAll/PerfilAPi/getInfoPerfil.php", getDatos);
            JsonObject jsonObject = JsonParser.parseString(consumoAPI.consumoGET("http://localhost/APIenPHP/getAll/PerfilAPi/getInfoPerfil.php", getDatos)).getAsJsonObject();
            JsonArray datosJson = jsonObject.get("data").getAsJsonArray();
            System.out.println(datosJson);
            JLNombre.setText(datosJson.get(0).getAsJsonObject().get("NombreVendedor").getAsString());
            JLParqueadero.setText(datosJson.get(0).getAsJsonObject().get("NombreParqueadero").getAsString());
            key_parqueadero = datosJson.get(0).getAsJsonObject().get("idpark").getAsString();
            idUser = datosJson.get(0).getAsJsonObject().get("idusuario").getAsString();
        }else{
            JLNombre.setText(username);
            JLParqueadero.setText(nombre_parqueadero);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorBtnNav = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        btnParquedero = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        JLImg = new javax.swing.JLabel();
        JLNombre = new javax.swing.JLabel();
        JLParqueadero = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        contentPanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedorBtnNav.setBackground(new java.awt.Color(17, 17, 17));
        contenedorBtnNav.setForeground(new java.awt.Color(255, 255, 255));

        btnDashboard.setBackground(new java.awt.Color(17, 17, 17));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("DASHBOARD");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnVehiculos.setBackground(new java.awt.Color(17, 17, 17));
        btnVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        btnVehiculos.setText("VEHICULOS");
        btnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosActionPerformed(evt);
            }
        });

        btnParquedero.setBackground(new java.awt.Color(17, 17, 17));
        btnParquedero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnParquedero.setForeground(new java.awt.Color(255, 255, 255));
        btnParquedero.setText("PARQUEADERO");
        btnParquedero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParquederoActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(17, 17, 17));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 51, 51));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        JLNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLNombre.setForeground(new java.awt.Color(255, 255, 255));
        JLNombre.setText("Nombre");

        JLParqueadero.setBackground(new java.awt.Color(153, 153, 153));
        JLParqueadero.setText("Parqueadero");

        javax.swing.GroupLayout contenedorBtnNavLayout = new javax.swing.GroupLayout(contenedorBtnNav);
        contenedorBtnNav.setLayout(contenedorBtnNavLayout);
        contenedorBtnNavLayout.setHorizontalGroup(
            contenedorBtnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorBtnNavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorBtnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorBtnNavLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(contenedorBtnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLParqueadero, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(contenedorBtnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnParquedero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLImg, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contenedorBtnNavLayout.setVerticalGroup(
            contenedorBtnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorBtnNavLayout.createSequentialGroup()
                .addGroup(contenedorBtnNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorBtnNavLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(JLImg, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenedorBtnNavLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(JLParqueadero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnParquedero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel1.setBackground(new java.awt.Color(18, 20, 28));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        contentPanel.setText("LABEL PRINICPAL SIN NADA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenedorBtnNav, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorBtnNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        contentPanel.removeAll();
        dashboardVen dash = new dashboardVen(key_parqueadero, idUser);
        dash.setSize(contentPanel.getSize());
        dash.setLocation(0, 0);
        contentPanel.add(dash);
        repaint();
        revalidate();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnParquederoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParquederoActionPerformed
        contentPanel.removeAll();
        InformarcionParqueadero infoDash = new InformarcionParqueadero(key_parqueadero, idUser);
        infoDash.setSize(contentPanel.getSize());
        infoDash.setLocation(0,0);
        contentPanel.add(infoDash);
        repaint();
        revalidate();
    }//GEN-LAST:event_btnParquederoActionPerformed

    private void btnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosActionPerformed
        contentPanel.removeAll();
        ListadoVehiculos listadoDash = new ListadoVehiculos(idUser, key_parqueadero);
        listadoDash.setSize(contentPanel.getSize());
        listadoDash.setLocation(0, 0);
        contentPanel.add(listadoDash);
        repaint();
        revalidate();
    }//GEN-LAST:event_btnVehiculosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplictionVen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplictionVen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplictionVen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplictionVen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplictionVen(null, null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLImg;
    private javax.swing.JLabel JLNombre;
    private javax.swing.JLabel JLParqueadero;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnParquedero;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JPanel contenedorBtnNav;
    private javax.swing.JLabel contentPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
